# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_instance_profile.jfrog-role:
resource "aws_iam_instance_profile" "jfrog-role" {
  name     = "jfrog-role"
  path     = "/"
  role     = aws_iam_role.jfrog-role.name
  tags     = {}
  tags_all = {}
}
