# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role_policy_attachment.jfrog-role__AmazonEC2FullAccess:
resource "aws_iam_role_policy_attachment" "jfrog-role__AmazonEC2FullAccess" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEC2FullAccess"
  role       = aws_iam_role.jfrog-role.id
}
