# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role_policy_attachment.jfrog-role__AWSSSODirectoryAdministrator:
resource "aws_iam_role_policy_attachment" "jfrog-role__AWSSSODirectoryAdministrator" {
  policy_arn = "arn:aws:iam::aws:policy/AWSSSODirectoryAdministrator"
  role       = aws_iam_role.jfrog-role.id
}
