# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_vpc_dhcp_options.dopt-04dfac881a9c71bfa:
resource "aws_vpc_dhcp_options" "dopt-04dfac881a9c71bfa" {
  domain_name = "us-west-2.compute.internal"
  domain_name_servers = [
    "AmazonProvidedDNS",
  ]
  tags     = {}
  tags_all = {}
}
