# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role.jfrog-role:
resource "aws_iam_role" "jfrog-role" {
  assume_role_policy = jsonencode(
    {
      Statement = [
        {
          Action = "sts:AssumeRole"
          Effect = "Allow"
          Principal = {
            Service = "ec2.amazonaws.com"
          }
        },
      ]
      Version = "2012-10-17"
    }
  )
  description           = "Allows EC2 instances to call AWS services on your behalf."
  force_detach_policies = false
  managed_policy_arns = [
    "arn:aws:iam::aws:policy/AWSHealthFullAccess",
    "arn:aws:iam::aws:policy/AWSSSODirectoryAdministrator",
    "arn:aws:iam::aws:policy/AmazonEC2FullAccess",
    "arn:aws:iam::aws:policy/AmazonRDSFullAccess",
    "arn:aws:iam::aws:policy/job-function/SupportUser",
  ]
  max_session_duration = 3600
  name                 = "jfrog-role"
  path                 = "/"
  tags                 = {}
  tags_all             = {}

  inline_policy {}
}
