# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table.rtb-01a18b121ab11643f:
resource "aws_route_table" "rtb-01a18b121ab11643f" {
  propagating_vgws = []
  route = [
    {
      carrier_gateway_id         = ""
      cidr_block                 = "0.0.0.0/0"
      core_network_arn           = ""
      destination_prefix_list_id = ""
      egress_only_gateway_id     = ""
      gateway_id                 = aws_internet_gateway.igw-050203062ea5fd49a.id
      instance_id                = null
      ipv6_cidr_block            = null
      local_gateway_id           = ""
      nat_gateway_id             = ""
      network_interface_id       = ""
      transit_gateway_id         = ""
      vpc_endpoint_id            = ""
      vpc_peering_connection_id  = ""
    },
  ]
  tags     = {}
  tags_all = {}
  vpc_id   = aws_vpc.vpc-0349a9202ee82357d.id

  timeouts {}
}
