# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_internet_gateway.igw-050203062ea5fd49a:
resource "aws_internet_gateway" "igw-050203062ea5fd49a" {
  tags     = {}
  tags_all = {}
  vpc_id   = aws_vpc.vpc-0349a9202ee82357d.id
}
