# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_default_network_acl.acl-0d432a08ea3204544:
resource "aws_default_network_acl" "acl-0d432a08ea3204544" {
  default_network_acl_id = "acl-0d432a08ea3204544"
  subnet_ids = [
    aws_subnet.subnet-008d9c21feddbf6a8.id,
    aws_subnet.subnet-069ee155c08cc089e.id,
    aws_subnet.subnet-0e6ff1a3b0baf3ff8.id,
    aws_subnet.subnet-0f7b9f347fd2fee01.id,
  ]
  tags     = {}
  tags_all = {}

  egress {
    action     = "allow"
    cidr_block = "0.0.0.0/0"
    from_port  = 0
    icmp_code  = 0
    icmp_type  = 0
    protocol   = "-1"
    rule_no    = 100
    to_port    = 0
  }

  ingress {
    action     = "allow"
    cidr_block = "0.0.0.0/0"
    from_port  = 0
    icmp_code  = 0
    icmp_type  = 0
    protocol   = "-1"
    rule_no    = 100
    to_port    = 0
  }
}
