# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_subnet.subnet-008d9c21feddbf6a8:
resource "aws_subnet" "subnet-008d9c21feddbf6a8" {
  assign_ipv6_address_on_creation                = false
  availability_zone                              = "us-west-2b"
  cidr_block                                     = "172.31.16.0/20"
  enable_dns64                                   = false
  enable_resource_name_dns_a_record_on_launch    = false
  enable_resource_name_dns_aaaa_record_on_launch = false
  ipv6_native                                    = false
  map_public_ip_on_launch                        = true
  private_dns_hostname_type_on_launch            = "ip-name"
  tags                                           = {}
  tags_all                                       = {}
  vpc_id                                         = aws_vpc.vpc-0349a9202ee82357d.id

  timeouts {}
}
