# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_lakeformation_data_lake_settings.c__781545506517:
resource "aws_lakeformation_data_lake_settings" "c__781545506517" {
  admins                  = []
  trusted_resource_owners = []

  create_database_default_permissions {
    permissions = [
      "ALL",
    ]
    principal = "IAM_ALLOWED_PRINCIPALS"
  }

  create_table_default_permissions {
    permissions = [
      "ALL",
    ]
    principal = "IAM_ALLOWED_PRINCIPALS"
  }
}
